Repository ThomasParistech/pretty-gpx, pull requests merged in 2024-11, with the labels that each got.

#48 refactor: Improve NiceGUI elements (UiInput / UiToggle)
  pretty_gpx/common/drawing/color_theme.py
  pretty_gpx/explore_new_color_themes.py
  pretty_gpx/rendering_modes/city/city_drawing_figure.py
  pretty_gpx/rendering_modes/city/city_poster_image_cache.py
  pretty_gpx/rendering_modes/city/drawing/city_colors.py
  pretty_gpx/rendering_modes/city/drawing/theme_colors.py
  pretty_gpx/rendering_modes/city/wip_city_sample.py
  pretty_gpx/rendering_modes/mountain/drawing/hillshading.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_colors.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawing_figure.py
  pretty_gpx/rendering_modes/mountain/drawing/theme_colors.py
  pretty_gpx/ui/pages/mountain/page.py
  pretty_gpx/ui/pages/template/elements/__init__.py
  pretty_gpx/ui/pages/template/elements/ui_input.py
  pretty_gpx/ui/pages/template/elements/ui_toggle.py
  pretty_gpx/ui/pages/template/ui_cache.py
  pretty_gpx/ui/pages/template/ui_manager.py
  pretty_gpx/ui/pages/template/ui_plot.py
Labels: refactor

#45 feat: add city page in gui
  examples/running/10 km Paris Centre.gpx
  examples/running/Semi_Marathon_de_Deauville.gpx
  examples/running/la-grande-classique-paris-versailles.gpx
  pretty_gpx/common/data/augmented_gpx_data.py
  pretty_gpx/common/data/overpass_processing.py
  pretty_gpx/common/layout/base_vertical_layout.py
  pretty_gpx/common/utils/utils.py
  pretty_gpx/explore_new_color_themes.py
  pretty_gpx/rendering_modes/city/data/augmented_gpx_data.py
  pretty_gpx/rendering_modes/city/data/city_augmented_gpx_data.py
  pretty_gpx/rendering_modes/city/drawing/city_drawer.py
  pretty_gpx/rendering_modes/city/drawing/city_drawing_cache_data.py
  pretty_gpx/rendering_modes/city/drawing/city_drawing_figure.py
  pretty_gpx/rendering_modes/city/wip_city_sample.py
  pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawing_cache_data.py
  pretty_gpx/ui/pages/city/page.py
  pretty_gpx/ui/pages/template/ui_cache.py
Labels: enhancement

#51 feat: Remove ui.pyplot and use rasterized plot with ui.image
  pretty_gpx/common/data/overpass_processing.py
  pretty_gpx/common/data/place_name.py
  pretty_gpx/common/drawing/base_drawing_figure.py
  pretty_gpx/common/drawing/drawing_data.py
  pretty_gpx/common/drawing/text_allocation.py
  pretty_gpx/common/layout/base_vertical_layout.py
  pretty_gpx/common/structure.py
  pretty_gpx/explore_new_color_themes.py
  pretty_gpx/rendering_modes/city/data/city_augmented_gpx_data.py
  pretty_gpx/rendering_modes/city/drawing/city_drawer.py
  pretty_gpx/rendering_modes/city/drawing/city_drawing_cache_data.py
  pretty_gpx/rendering_modes/city/drawing/city_drawing_figure.py
  pretty_gpx/rendering_modes/city/drawing/city_drawing_params.py
  pretty_gpx/rendering_modes/city/wip_city_sample.py
  pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawing_cache_data.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawing_config.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawing_figure.py
  pretty_gpx/ui/pages/city/page.py
  pretty_gpx/ui/pages/mountain/page.py
  pretty_gpx/ui/pages/template/ui_cache.py
  pretty_gpx/ui/pages/template/ui_manager.py
  pretty_gpx/ui/pages/template/ui_plot.py
  pretty_gpx/ui/utils/run.py
Labels: enhancement

#52 ci: bump python 3.10 to 3.11
  .devcontainer/Dockerfile
  .github/workflows/check.yml
  .vscode/.mypy.ini
  pretty_gpx/common/drawing/color_theme.py
  pretty_gpx/common/structure.py
  pretty_gpx/ui/pages/template/elements/ui_input.py
  pretty_gpx/ui/pages/template/elements/ui_toggle.py
  pretty_gpx/ui/pages/template/ui_cache.py
Labels: CI/CD

#53 ci: Python 3.11
  README.md
  pyproject.toml
Labels: CI/CD

#54 perf: Use agg backend mode
  pretty_gpx/rendering_modes/city/drawing/city_drawer.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py
  pretty_gpx/ui/pages/template/ui_plot.py
Labels: performance

#55 fix: Fix missing Col des Boeufs/Col d'Azet and use correct XY distance from lat/lon
  pretty_gpx/common/data/overpass_request.py
  pretty_gpx/common/gpx/gpx_bounds.py
  pretty_gpx/common/gpx/gpx_distance.py
  pretty_gpx/common/gpx/gpx_track.py
  pretty_gpx/common/layout/base_vertical_layout.py
  pretty_gpx/common/utils/asserts.py
  pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py
Labels: bug

#57 feat: Draw arrows pointing at mountain passes
  pretty_gpx/common/drawing/base_drawing_figure.py
  pretty_gpx/common/drawing/drawing_data.py
  pretty_gpx/common/drawing/fonts.py
  pretty_gpx/common/drawing/text_allocation.py
  pretty_gpx/common/gpx/gpx_bounds.py
  pretty_gpx/common/gpx/gpx_distance.py
  pretty_gpx/rendering_modes/city/drawing/city_drawer.py
  pretty_gpx/rendering_modes/city/drawing/city_drawing_config.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawing_config.py
Labels: enhancement

#58 docs: add city mode in doc
  README.md
  doc/posters/city/deauville.svg
  doc/posters/city/route_des_4_chateaux.svg
  doc/posters/couillole.svg
  doc/posters/diagonale-des-fous.svg
  doc/posters/marmotte.svg
  doc/posters/mountain/couillole.svg
  doc/posters/mountain/diagonale-des-fous.svg
  doc/posters/mountain/marmotte.svg
  doc/posters/mountain/peyresourde.svg
  doc/posters/mountain/vanoise_3days.svg
  doc/posters/peyresourde.svg
  doc/posters/vanoise_3days.svg
  examples/running/chicago_marathon.gpx
  examples/running/london_marathon.gpx
Labels: documentation

#60 perf: pass directly the binary into json
  pretty_gpx/common/data/overpass_request.py
Labels: performance

#61 perf: Use faster OverpassQuery for mountain huts and passes
  pretty_gpx/common/data/overpass_request.py
  pretty_gpx/common/data/place_name.py
  pretty_gpx/common/drawing/text_allocation.py
  pretty_gpx/common/utils/profile.py
  pretty_gpx/rendering_modes/city/data/forests.py
  pretty_gpx/rendering_modes/city/data/rivers.py
  pretty_gpx/rendering_modes/city/data/roads.py
  pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py
  pretty_gpx/rendering_modes/mountain/data/mountain_huts.py
  pretty_gpx/rendering_modes/mountain/data/mountain_passes.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py
Labels: performance

#63 feat: Split modal message into load/download/process
  pretty_gpx/common/structure.py
  pretty_gpx/explore_new_color_themes.py
  pretty_gpx/rendering_modes/city/data/city_augmented_gpx_data.py
  pretty_gpx/rendering_modes/city/drawing/city_download_data.py
  pretty_gpx/rendering_modes/city/drawing/city_drawer.py
  pretty_gpx/rendering_modes/city/drawing/city_drawing_figure.py
  pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py
  pretty_gpx/rendering_modes/mountain/data/mountain_huts.py
  pretty_gpx/rendering_modes/mountain/data/mountain_passes.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_download_data.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py
  pretty_gpx/ui/pages/template/ui_cache.py
  pretty_gpx/ui/pages/template/ui_plot.py
  pretty_gpx/ui/utils/modal.py
  pretty_gpx/ui/utils/run.py
Labels: enhancement

#66 docs: add more marathon GPX examples
  examples/running/10k_paris.gpx
  examples/running/half_marathon_deauville.gpx
  examples/running/marathon_berlin.gpx
  examples/running/marathon_bordeaux.gpx
  examples/running/marathon_chicago.gpx
  examples/running/marathon_london.gpx
  examples/running/marathon_new_york.gpx
  examples/running/marathon_nice_cannes.gpx
  examples/running/marathon_rennes.gpx
  examples/running/paris_versailles.gpx
Labels: documentation

#68 feat: Detect City Bridges
  pretty_gpx/common/gpx/gpx_distance.py
  pretty_gpx/rendering_modes/city/data/bridges.py
Labels: enhancement

#69 test: Add Pytests
  .devcontainer/requirements.txt
  .github/workflows/check.yml
  pretty_gpx/common/utils/asserts.py
  pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py
  pretty_gpx/test/__init__.py
  pretty_gpx/test/test_bridges.py
  pretty_gpx/test/test_city_pois.py
  pretty_gpx/test/test_mountain_passes.py
  scripts/run_pytest.sh
Labels: test

#62 perf: Simplify roads to reduce vectorized image size
  .devcontainer/requirements.txt
  .vscode/.mypy.ini
  pretty_gpx/common/data/overpass_processing.py
  pretty_gpx/common/data/overpass_request.py
  pretty_gpx/common/utils/utils.py
  pretty_gpx/fly/fly_io_setup.py
Labels: performance

#71 refactor: Compute Annotation Arrows inside text_allocation
  pretty_gpx/common/drawing/text_allocation.py
  pretty_gpx/common/gpx/gpx_distance.py
  pretty_gpx/common/gpx/gpx_track.py
  pretty_gpx/common/structure.py
  pretty_gpx/common/utils/plt.py
  pretty_gpx/rendering_modes/city/data/bridges.py
  pretty_gpx/rendering_modes/city/data/city_pois.py
  pretty_gpx/rendering_modes/mountain/data/mountain_augmented_gpx_data.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_drawer.py
Labels: refactor

#72 test: add pytests for city/mountain cache ui
  pretty_gpx/test/test_city_ui.py
  pretty_gpx/test/test_mountain_ui.py
  scripts/run_mypy.sh
Labels: test

#73 fix: Correctly handle vertical alignment in textalloc
  .devcontainer/requirements.txt
Labels: bug
