Repository ThomasParistech/pretty-gpx, pull requests merged in 2024-10, with the labels that each got.

#19 perf: Do a single overpass request in city mode
  .devcontainer/requirements.txt
  pretty_gpx/city/data/rivers.py
  pretty_gpx/city/data/roads.py
  pretty_gpx/city/wip_city_sample.py
  pretty_gpx/common/data/overpass_request.py
Labels: performance

#25 fix: Support empty arrays if no river is in the map
  pretty_gpx/common/data/overpass_request.py
Labels: bug

#26 feat: add ocean/bay and add small rivers
  pretty_gpx/city/data/rivers.py
  pretty_gpx/common/data/overpass_processing.py
Labels: enhancement

#27 perf: update merging algorithm
  pretty_gpx/common/data/overpass_processing.py
  pretty_gpx/common/data/overpass_request.py
  pretty_gpx/common/utils/utils.py
Labels: performance

#28 feat: add forests
  examples/running/route_4_chateaux.gpx
  pretty_gpx/city/city_drawing_figure.py
  pretty_gpx/city/data/forests.py
  pretty_gpx/city/data/rivers.py
  pretty_gpx/city/drawing/theme_colors.py
  pretty_gpx/city/wip_city_sample.py
  pretty_gpx/common/data/overpass_processing.py
  pretty_gpx/common/data/overpass_request.py
  pretty_gpx/common/utils/utils.py
Labels: enhancement

#30 feat: Catch errors during file processing
  pretty_gpx/common/data/overpass_request.py
  pretty_gpx/common/gpx/gpx_bounds.py
  pretty_gpx/common/gpx/gpx_track.py
  pretty_gpx/common/layout/base_vertical_layout.py
  pretty_gpx/common/utils/logger.py
  pretty_gpx/common/utils/nicegui_helper.py
  pretty_gpx/main.py
  pretty_gpx/mountain/data/augmented_gpx_data.py
  pretty_gpx/mountain/data/elevation_map.py
  pretty_gpx/mountain/drawing/poster_image_cache.py
Labels: enhancement

#31 perf: Speed up elevation profile fillPoly
  pretty_gpx/common/drawing/elevation_stats_section.py
  pretty_gpx/common/gpx/gpx_bounds.py
  pretty_gpx/common/layout/elevation_vertical_layout.py
  pretty_gpx/mountain/drawing/poster_image_cache.py
  pretty_gpx/mountain/mountain_vertical_layout.py
Labels: performance

#32 perf: Actually use the ele poly simplifcation!
  pretty_gpx/city/city_vertical_layout.py
  pretty_gpx/city/wip_city_sample.py
  pretty_gpx/mountain/drawing/poster_image_cache.py
Labels: performance

#34 feat: Deploy app on fly.io
  .devcontainer/Dockerfile
  .devcontainer/packages.txt
  .devcontainer/requirements.txt
  fly.toml
Labels: enhancement

#37 fix: elevation downsampling
  pretty_gpx/common/drawing/elevation_stats_section.py
Labels: bug

#39 refactor: Prepare the city gui
  pretty_gpx/explore_new_color_themes.py
  pretty_gpx/main.py
  pretty_gpx/rendering_modes/city/city_drawing_figure.py
  pretty_gpx/rendering_modes/city/drawing/city_drawing_params.py
  pretty_gpx/rendering_modes/city/wip_city_sample.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_poster_image_cache.py
Labels: refactor

#38 fix: Draw small rivers in front of forests, remove rivers in tunnels
  pretty_gpx/common/gpx/gpx_bounds.py
  pretty_gpx/rendering_modes/city/city_drawing_figure.py
  pretty_gpx/rendering_modes/city/data/rivers.py
  pretty_gpx/rendering_modes/city/wip_city_sample.py
Labels: bug

#41 feat: enhance support for duration with a 2 stats line layout
  pretty_gpx/rendering_modes/city/city_vertical_layout.py
  pretty_gpx/rendering_modes/city/wip_city_sample.py
Labels: enhancement

#44 fix: handle case when user gives float instead of int
  pretty_gpx/rendering_modes/city/city_poster_image_cache.py
  pretty_gpx/rendering_modes/mountain/drawing/mountain_poster_image_cache.py
Labels: bug

#47 perf: Use Multiple fly.io Instances and Lighten Docker image
  .devcontainer/requirements.txt
  .dockerignore
  .vscode/.mypy.ini
  pretty_gpx/fly/__init__.py
  pretty_gpx/fly/fly_io_setup.py
  pretty_gpx/main.py
  pretty_gpx/simplify_gpx.py
  scripts/fly_deploy.sh
Labels: performance
