Repository ThomasParistech/pretty-gpx, pull requests merged in 2024-09, with the labels that each got.

#8 ci: Add PR check GitHub action + Fix Linter/TypeChecker for the codebase + Refactor PosterImageCache
  .github/pull_request_template.md
  .github/workflows/check.yml
  .github/workflows/validate-pr-title.yml
  .vscode/.mypy.ini
  .vscode/ruff.toml
  README.md
  pretty_gpx/drawing/drawing_data.py
  pretty_gpx/drawing/poster_image_cache.py
  pretty_gpx/drawing/text_allocation.py
  pretty_gpx/gpx/augmented_gpx_data.py
  pretty_gpx/gpx/elevation_map.py
  pretty_gpx/gpx/gpx_io.py
  pretty_gpx/gpx/gpx_track.py
  pretty_gpx/main.py
  pretty_gpx/simplify_gpx.py
  pretty_gpx/utils/asserts.py
  scripts/run_linter.sh
  scripts/run_mypy.sh
Labels: CI/CD

#10 fix: use uphill_m instead of list_cumul_ele and refacto list_cumul_d
  .github/workflows/check.yml
  pretty_gpx/drawing/poster_image_cache.py
  pretty_gpx/gpx/augmented_gpx_data.py
  pretty_gpx/gpx/gpx_track.py
  pretty_gpx/utils/asserts.py
Labels: bug

#11 ci: Run linter check when pushing to main
  .github/workflows/check.yml
Labels: CI/CD

#12 refactor: Refactor to allow other maps than mountain
  pretty_gpx/common/__init__.py
  pretty_gpx/common/drawing/__init__.py
  pretty_gpx/common/drawing/base_drawing_figure.py
  pretty_gpx/common/drawing/drawing_data.py
  pretty_gpx/common/drawing/plt_marker.py
  pretty_gpx/common/drawing/text_allocation.py
  pretty_gpx/common/gpx/__init__.py
  pretty_gpx/common/gpx/gpx_bounds.py
  pretty_gpx/common/gpx/gpx_data_cache_handler.py
  pretty_gpx/common/gpx/gpx_io.py
  pretty_gpx/common/gpx/gpx_track.py
  pretty_gpx/common/gpx/overpass.py
  pretty_gpx/common/layout/__init__.py
  pretty_gpx/common/layout/base_vertical_layout.py
  pretty_gpx/common/layout/paper_size.py
  pretty_gpx/common/utils/__init__.py
  pretty_gpx/common/utils/asserts.py
  pretty_gpx/common/utils/logger.py
  pretty_gpx/common/utils/paths.py
  pretty_gpx/common/utils/profile.py
  pretty_gpx/common/utils/ui_helper.py
  pretty_gpx/common/utils/utils.py
  pretty_gpx/drawing/drawing_data.py
  pretty_gpx/drawing/drawing_figure.py
  pretty_gpx/drawing/drawing_params.py
  pretty_gpx/explore_new_color_themes.py
  pretty_gpx/gpx/gpx_bounds.py
  pretty_gpx/layout/vertical_layout.py
  pretty_gpx/main.py
  pretty_gpx/mountain/__init__.py
  pretty_gpx/mountain/augmented_gpx_data.py
  pretty_gpx/mountain/drawing/__init__.py
  pretty_gpx/mountain/drawing/hillshading.py
  pretty_gpx/mountain/drawing/mountain_drawing_figure.py
  pretty_gpx/mountain/drawing/mountain_drawing_params.py
  pretty_gpx/mountain/drawing/poster_image_cache.py
  pretty_gpx/mountain/drawing/theme_colors.py
  pretty_gpx/mountain/elevation_map.py
  pretty_gpx/mountain/mountain_vertical_layout.py
  pretty_gpx/simplify_gpx.py
Labels: refactor

#13 perf: Improve drawing figure perf
  pretty_gpx/common/drawing/drawing_data.py
  pretty_gpx/mountain/augmented_gpx_data.py
  pretty_gpx/mountain/drawing/poster_image_cache.py
  pretty_gpx/mountain/mountain_vertical_layout.py
Labels: performance

#16 feat: Avoid text alloc crossing lines
  .devcontainer/requirements.txt
  .github/pull_request_template.md
  examples/hiking/utmb.gpx
  pretty_gpx/common/drawing/text_allocation.py
  pretty_gpx/common/layout/base_vertical_layout.py
Labels: enhancement

#17 feat: ✨ Add rivers in city mode
  .devcontainer/requirements.txt
  pretty_gpx/city/city_drawing_figure.py
  pretty_gpx/city/data/rivers.py
  pretty_gpx/city/drawing/theme_colors.py
  pretty_gpx/city/wip_city_sample.py
  pretty_gpx/common/data/overpass_processing.py
  pretty_gpx/common/drawing/drawing_data.py
Labels: enhancement

#20 perf: Add profiler
  .vscode/.mypy.ini
  .vscode/ruff.toml
  pretty_gpx/city/data/rivers.py
  pretty_gpx/city/data/roads.py
  pretty_gpx/city/wip_city_sample.py
  pretty_gpx/common/data/overpass_processing.py
  pretty_gpx/common/data/overpass_request.py
  pretty_gpx/common/drawing/base_drawing_figure.py
  pretty_gpx/common/drawing/drawing_data.py
  pretty_gpx/common/drawing/text_allocation.py
  pretty_gpx/common/gpx/gpx_data_cache_handler.py
  pretty_gpx/common/gpx/gpx_track.py
  pretty_gpx/common/utils/asserts.py
  pretty_gpx/common/utils/logger.py
  pretty_gpx/common/utils/nicegui_helper.py
  pretty_gpx/common/utils/pickle_io.py
  pretty_gpx/common/utils/profile.py
  pretty_gpx/common/utils/ui_helper.py
  pretty_gpx/common/utils/utils.py
  pretty_gpx/main.py
  pretty_gpx/mountain/data/augmented_gpx_data.py
  pretty_gpx/mountain/data/elevation_map.py
  pretty_gpx/mountain/drawing/mountain_drawing_figure.py
  pretty_gpx/mountain/drawing/poster_image_cache.py
  pretty_gpx/simplify_gpx.py
Labels: performance
